DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS images;

CREATE TABLE user (
  ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL
);

CREATE TABLE images (
  ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  img_path VARCHAR(260) NULL UNIQUE,
  img_name VARCHAR(260) NULL,
  FOREIGN KEY (user_id) REFERENCES user (ID)
);